### ISSUE TITLE
'markersAreaEnabled' / 'minConfidence' parameter is undefined.

### ISSUE THREAD

**Issue by dirkk0** [AR-js-org/studio#106]
Hi!

Great idea! But the exported project is not working here.

The console shows:
aframe-ar.js:2023 THREEx.ArMarkerControls: 'markersAreaEnabled' is not a property of this material.
and
aframe-ar.js:2016 THREEx.ArMarkerControls: 'minConfidence' parameter is undefined.

This was a Hiro marker plus glTF model in glb format.

I attached the project for reference.

Thanks, Dirk
[ar.zip](https://github.com/AR-js-org/studio/files/5566966/ar.zip)

**Comment by gciandro13** [comment]
Seeing the logs I guess that this could be a problem related to arjs (I ask to @nicolocarpignoli ) 
We will focus on that and we'll give you update @dirkk0 

Ty

**Comment by nicolocarpignoli** [comment]
@dirkk0 those warnings should not be a problem.

Can you please host the project and give us:

- a live example that we can run
- the marker image, not only  the .patt

I see no problems on the code but we need those two things in order to test better.

**Comment by dirkk0** [comment]
Sure thing!
Here's the link to the hosted project:
http://curious-electric.com/_del/ar-test/
and this is the marker:
https://stemkoski.github.io/AR-Examples/markers/hiro.png

Just for reference, the Stemkoski examples are working:
https://stemkoski.github.io/AR-Examples/

**Comment by nicolocarpignoli** [comment]
the problem is that you are using a HIRO marker but as a 'pattern' marker. Artoolkit fails to recognize it (if you look the .patt file with VSCode you will see the 'hiro' letters are not interpreted).

So you either use a different marker (like the default that Studio suggests you) ore you modify your code (HTML) in order to handle the default HIRO marker (you can find examples on the AR.js docs ) like this:

```
<!DOCTYPE html>
<html>
  <script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
  <!-- we import arjs version without NFT but with marker + location based support -->
  <script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js"></script>
  <body style="margin : 0px; overflow: hidden;">
    <a-scene embedded arjs>
      <a-marker preset="hiro">
        <a-entity
          position="0 0 0"
          scale="0.05 0.05 0.05"
          gltf-model="https://arjs-cors-proxy.herokuapp.com/https://raw.githack.com/AR-js-org/AR.js/master/aframe/examples/image-tracking/nft/trex/scene.gltf"
        ></a-entity>
      </a-marker>
      <a-entity camera></a-entity>
    </a-scene>
  </body>
</html>
```

(consider only the preset='hiro' part and replace only that)

**Comment by dirkk0** [comment]
Ah ok, thanks for looking into this.
Programming this myself/ changing the code is not a problem for me, I did so several times before.

But I liked the idea of having a wizard doing that without having to bother with code.
The wizard prompts me to upload an image as a marker, which I did.
So I guess this is an issue with Studio's wizard, right?
![image](https://user-images.githubusercontent.com/625394/100730439-5789ef80-33ca-11eb-9f7b-b936a5cb4b16.png)

**Comment by nicolocarpignoli** [comment]
Yes, it's a particular case when the user uploads on of the 'two' premade markers (Hiro and Kanjii ones). In those case, it may fail :)

**Comment by nicolocarpignoli** [comment]
@gciandro13 we should modify the 'guide' (the linked one) and state to NOT use HIRO marker (also include the HIRO marker image as a lot of users mistake this with barcodes).

Please  open a new issue  with this little enhancement

**Comment by gciandro13** [comment]
Related issue: https://github.com/AR-js-org/studio/issues/109 

Thanks @dirkk0  @nicolocarpignoli
