### ISSUE TITLE
Can't use latitude of south hemisphere

### ISSUE THREAD

**Issue by jbonomo1982** [AR-js-org/studio#107]
Hi!
When I try to use Ar.js studio location based with coordinates on the south hemisphere (e.g. -43.89789239125797 ; -57.52441406250001) I can´t export the project, if I change the coordinates to north hemisphere i can export it easily. Can you help me with this?
Many thanks in advance! 

Juan M. Bonomo

**Comment by gciandro13** [comment]
Hi @jbonomo1982  issue is already open: https://github.com/AR-js-org/studio/issues/77 . 
We will take updates on it , thanks.
