### ISSUE TITLE
AR.js web interface does not allow download for southern hemisphere. 

### ISSUE THREAD

**Issue by mjldunn** [AR-js-org/studio#110]
Using the ar.js studio ( https://ar-js-org.github.io/studio/pages/location/index.html )

I tried to use my location in the web interface ( the south west of Western Australia). When I select it on the map the button to download the project does nothing.  I tried moving the Latitude > 0 and the button started working 

So for an Latitude<0 i.e  Southern hemisphere the download does not work. 

I wonder if this is specific to the web interface or is an error in the ar.js code as well. I have tried multiple times to get it to work at my location and it has not worked.

**Comment by gciandro13** [comment]
Hi @mjldunn  , that issue is already open. We will take care of that asap. https://github.com/AR-js-org/studio/issues/77
Thank you.
