### ISSUE TITLE
Marker Tracker 

### ISSUE THREAD

**Issue by eredeli** [AR-js-org/studio#114]
Hello everything works great! Love it! But the video (.mp4) on the marker tracker is very chaotic, because the code uses the video as a function of seeing a 3D object, as I understand it, and the video shakes every time, can't watch it. I only need to use video, no 3D objects, where can I change it? it must be shown at a fixed location. 

Thank you,

Levan

**Comment by gciandro13** [comment]
Hi @eredeli  !
Please feel free to open a pull request if you want to improve the actual code-base. 
It will be discussed and eventually accepted by our admin. 
Thank for the feedback
