### ISSUE TITLE
Publish on github directly did not work

### ISSUE THREAD

**Issue by JavierR2** [AR-js-org/studio#117]
Publish on github directly or download package did not work. The buttons are as off. I click on them and nothing happens. I tried different browsers and none works for me.

**Comment by gciandro13** [comment]
Hi @JavierR2  this is linked to other issues.
HAve you tried several times ? Please share the console error if you are not able to publish anymore.
Bye

**Comment by ilmalte** [comment]
Hey @gciandro13 I second this. After Github OAuth this is the console output:

![image](https://user-images.githubusercontent.com/17677294/127778698-bc48a919-df4d-40eb-acee-6ad107208aeb.png)
![image](https://user-images.githubusercontent.com/17677294/127778706-90cad060-3658-4787-a066-257b22a4281b.png)

**Comment by pinkguavaaaa** [comment]
i'm also having the same issue as above, anyone can advice on next steps for such scenarios? uploaded project - marker base, uploaded image and zip file, signed up github and this page have been the same after multiple hours/tries on different internet provider/location.
<img width="1326" alt="Screenshot 2023-05-15 at 12 26 10 AM" src="https://github.com/AR-js-org/studio/assets/133185087/32e56bb9-034c-4cdc-af55-5a9bb69ce909">

**Comment by kalwalt** [comment]
> i'm also having the same issue as above, anyone can advice on next steps for such scenarios? uploaded project - marker base, uploaded image and zip file, signed up github and this page have been the same after multiple hours/tries on different internet provider/location.
> <img width="1326" alt="Screenshot 2023-05-15 at 12 26 10 AM" src="https://github.com/AR-js-org/studio/assets/133185087/32e56bb9-034c-4cdc-af55-5a9bb69ce909">
> 

I think It Is related to issue #122

**Comment by gciandro13** [comment]
issue #122
