### ISSUE TITLE
Infinitely Loads.

### ISSUE THREAD

**Issue by GidRedstone** [AR-js-org/studio#122]
![image](https://user-images.githubusercontent.com/35389967/218588236-622e1257-5274-4129-ac9e-7db4993f2bae.png)
It infinitely Loads and when I look in the Console (Image above) it says that and yeah that's basically it. Just doesn't load.

**Comment by kalwalt** [comment]
heroku has discontinued the opensource option, so i think the app won't work anymore. @nicolocarpignoli or other `studio` developers maybe know an alternative. Unfortunately i didn't partecipate in this, so i ca not say so much... 🥲

**Comment by MarcosGuillherme** [comment]
I makes a workaround downloaded the project and upload at github after in the settings, I created the github pages. its the same thing with automation on arjs studio I guess

**Comment by gciandro13** [comment]
Hi everyone, i will take in account this issue to make AR-studio work again.
It's a heroku error of the deploied backend!

**Comment by nicolocarpignoli** [comment]
It is now working again with a private node server. I also added a Readme section about this, as the private server is not guaranteed to last.
