### ISSUE TITLE
CORS Error when download package and launch index.html in local

### ISSUE THREAD

**Issue by gciandro13** [AR-js-org/studio#123]
Both in location and marker based zip package download, when launch the index.html cors error happened.

![image](https://github.com/AR-js-org/studio/assets/20702863/1bb6dd33-095e-42ce-b326-13b362f119da)

**Comment by nicolocarpignoli** [comment]
It is now working again with a private node server. I also added a Readme section about this, as the private server is not guaranteed to last.
