### ISSUE TITLE
Constraints for upload of files for MVP

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/studio#14]
We have to define constraints for file to be uploaded on the studio project.

This is for the MVP. After the MPV, will be added more.

Actually, for MVP I was thinking of:

 - Size Limit: 25 MB for EVERY kind of file

- Audio: .mp3
- Video: .mp4
- Images: .jpg, .png, .gif
- 3D Models: .gltf/.glb

**Comment by iburguera** [comment]
Would also take into account the number of polygons and triangles of the GLTF/GLB model? I guess that a 25MB doesn't have much polygon and the size of the object is more related to the textures.

**Comment by nicolocarpignoli** [comment]
It would be much more easy to check the file size. Please suggest a reasonable limit for 3D model size instead of 25 MB that we can set for the MVP.

**Comment by iburguera** [comment]
This are my considerations for each type of file that make sense to me: 

- Audio: .mp3  (10MB Max)

The average song length is 3 minutes and thirty seconds, according to google. This translates into 210 seconds. Audio with 128 kbps takes about 1MB per minute so 10 minute sonf is more than enough.

- Video: .mp4 (25MB Max)

A very good 1080p video with x264/h264 (mp4 or mkv), may need at least 3500kbps in resolution. That means about 25mb in filesize per minute (only video). I would consider just uploading 720p (or less) videos to get more minutes. 

- Images: .jpg, .png, .gif (15 MB Max)

You can take up to 12MB with 3000x1500px and 300ppi. For MVP purpose is more than enough.

- 3D Models: .gltf/.glb (50MB max)

Models downloaded from Google Poly: No problem, they are Low-Poly and small textures
Models downloaded from Sketchfab or other 3D service: High Poly and big textures. 

Fell free to ad any comments

**Comment by nicolocarpignoli** [comment]
Ok, design guys have implemented this one on the dropdown to choose the content to upload. Thank you @iburguera
