### ISSUE TITLE
Create the 2D map embed on Location page

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/studio#17]
Following Figma design: https://www.figma.com/file/TUjZ2KYsmhA5LUkt9KIhcB/ARjs-Components?node-id=0%3A1

On this issue, it's required to implement the 2D map. 
If the marker is customizable, it should be something like the yellow marker on the Figma design.

![image](https://user-images.githubusercontent.com/22395670/75573942-2a389b80-5a5e-11ea-906a-6eee6ec06080.png)

Clicking on the map, some data are outputed (latitude, longitude), and will appear on a div under the map (see the image).

**Comment by nicolocarpignoli** [comment]
I need a bit of help: what is, from your experience, the easiest way, in vanilla JS, to create a 2D map, where 

* clicking on it, I can add a marker (as above) 
* and retrieve latitude/longitude of the clicked point? 

Any library/suggestion is welcome!

@sinanatra
@edoardocavazza

**Comment by edoardocavazza** [comment]
I think that the simplest path is to use the Leaflet library with OpenStreet Maps as provider. It does not require any access token but if you want to customize the map there are some limitations. Mapbox GL is cooler but it requires an access token.

**Comment by sinanatra** [comment]
I agree with @edoardocavazza , mapbox's quite better but in this case it might be an overkill

**Comment by nicolocarpignoli** [comment]
Thank you guys. I will also make this a Web Component in order to use it in different views.

**Comment by ba5eem** [comment]
<img width="913" alt="arjs-map" src="https://user-images.githubusercontent.com/29417257/77862963-9839c500-71ba-11ea-8f23-a6ca0d7c8a14.png">

I added the map using Leaflet - I tried to make it re-useable as possible, open to any feedback or suggestions. Once user clicks on the map a marker will show up and update lat/lng coords in the input values as well. 

its under a new branch called feature/leafletmap

**Comment by fcor** [comment]
@ba5eem Awesome! I'll take a look 😃

**Comment by fcor** [comment]
@ba5eem Didn't find the branch, could you create a PR?

**Comment by ba5eem** [comment]
sorry - check now. was re-reading contributing guidelines to make sure I did it right. I just pushed the branch.

**Comment by ba5eem** [comment]
I had an additional thought about the map: right now its set to a random spot in Hawaii - to make it more relevant to each user, should I implement geolocation to get users location as the map starting area on load.

**Comment by fcor** [comment]
That would be great! Also, would be possible to write lat/long coordinates and position the map according to them as well? 

Looks good!

**Comment by kalwalt** [comment]
@ba5eem i will check tomorrow this, too late now here!

**Comment by mingir2** [comment]
@ba5eem Looks great!

The most recent wire on Figma has the geolocation feature for the map. So, geolocation API would be the way to go. If you like, you can probably keep the default to be where it is now :)
![LOCATION - Success](https://user-images.githubusercontent.com/40753283/77863666-8c192c00-71e9-11ea-80d1-1d87c3cec987.png)

This isn't a big deal, but I was wondering if it's necessary to have both of these stylesheet imports.
```js
//map-pick-location.js 
const leaflet_stylesheet_link = `<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
   integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
   crossorigin=""/>`;
```

```html
<!-- location.html -->
 <!-- import the leaflet css and script -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
   integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
   crossorigin=""/>
```

**Comment by ba5eem** [comment]
@mingir2 thanks for the feedback. 
I know some people are concerned for privacy reason for accepting location on prompt, so I can include it - but if they deny access, or have it previously deny all as their default in their browser we could implement on 'get' on the backend to use the ISP IP as the general area for the map location, so they don't have to pan all over the globe to their location i suppose could be one option.

In regards to the stylesheet imports - I tried importing it just once, but noticed with it on the // map-pick-location.js file it works for loading the map tiles, but then when clicked it would report 'marker icon' not found which is why I included it in the location.html file as well to resolve that issue - something to do with the order of the component mounting/connecting - not sure how it works, maybe someone else can figure out the correct order to eliminate one of the imports.

**Comment by ba5eem** [comment]
<img width="834" alt="approved" src="https://user-images.githubusercontent.com/29417257/77912144-ba205f80-722d-11ea-948f-a0f45be70baa.png">
So above is the implementation of clicking 'set location' will utilize the navigator.geolocation api.
once location found the map will pan to center around found coordinates.

<img width="889" alt="denied" src="https://user-images.githubusercontent.com/29417257/77912233-e3d98680-722d-11ea-98c1-e71dbd942b8b.png">

the above shows - that if they click 'set location' and they have default to deny location, it will provide minimal guidance on changing it for this page only. but they can always still just pan themselves and click on the map is suppose.

i updated the feature branch - and re-looked at the figma image - and then realized 'set location' is 'im complete move to next step button and that you have a 'use my location' button on the map - ill have to change it - will update soon.

**Comment by kalwalt** [comment]
@ba5eem i can confirm that if you click on the map it will be added the location blu flag and a message appear if you set the location:
`Location is set to: 21.290164091856454, -157.82986879348758!` i found difficult to scroll from the desired location Italy, the zoom don't let too much freedom at the moment.

**Comment by kalwalt** [comment]
To be clear: i was refering to the Zoom out feature.  You can Zooming out until a certain point and then it stops, so you can't view the whole earth map.

**Comment by nicolocarpignoli** [comment]
@ba5eem be aware to modifies added to master recently, probably you have to align

**Comment by ba5eem** [comment]
@kalwalt i removed zoom out limitation, it was just a default attribute option 'minzoom', i commented it out. also am updating the branch to match the figma - with button on the map.
- updated button with working to match figma
- used svg icon button
- button still gets user location
- TODO: change css location of button
- branch updated

thanks @nicolocarpignoli for the heads up about master updates, they have been included.

hope everyone is safe and healthy! its getting spooky here in hawaii

**Comment by nicolocarpignoli** [comment]
@ba5eem how is it going? Are you able to make a PR for this? thank you!

**Comment by ba5eem** [comment]
Aloha! 
Yep. I can by this weekend. Does that work? 

Mahalo

**Comment by nicolocarpignoli** [comment]
Absolutely!

**Comment by ba5eem** [comment]
I moved the use my location to the map bottom right corner to match the figma, is the 'Set Location' button also part of this issue? just checking before submitting a pull request
