### ISSUE TITLE
Create footer (Export the project panel)

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/studio#20]
Following Figma design: https://www.figma.com/file/TUjZ2KYsmhA5LUkt9KIhcB/ARjs-Components?node-id=0%3A1

It's required to implement the footer panel, the one where the user can export the project. The two actions to be triggered on the buttons' click will be handled on separate issues.

![image](https://user-images.githubusercontent.com/22395670/75574435-94e9d700-5a5e-11ea-86cc-b7954d922892.png)

**Comment by nicolocarpignoli** [comment]
This is a good example for using Web Components, because this piece of view is replicated exactly on different pages. So, to not copy and paste html and js code, we can use a web component https://developer.mozilla.org/it/docs/Web/Web_Components

If you want @thauska you can simply create the html snippet plus js code and I can make it a web component, you tell me.😊

**Comment by thauska** [comment]
I can create the html snippet, is better for me.

**Comment by nicolocarpignoli** [comment]
@thauska how is it going? :) If you need help, just ask

**Comment by thauska** [comment]
I've created the branch issue#20 and started creating the footer.

**Comment by thauska** [comment]
Let me know if I'm doing good

**Comment by thauska** [comment]
#34

**Comment by thauska** [comment]
I have closed the PR and created the branch here on the original repo. Haven't seen that I've permission to create new branches.

https://github.com/AR-js-org/studio/tree/issue%2320

**Comment by nicolocarpignoli** [comment]
Thank you! Merged
