### ISSUE TITLE
Github page 404 on resources

### ISSUE THREAD

**Issue by mingir2** [AR-js-org/studio#30]
GitHub pages absolute path starts from https://ar-js-org.github.io/studio/ rather than https://ar-js-org.github.io/. As a result, we get 404 for the resource that are pointing to the root directory (https://ar-js-org.github.io/).

In #29, I changed every relative path to absolute path in order to use same header component for each pages, but I didn't account for /studio/ directory.

**Comment by mingir2** [comment]
It seems like I've actually changed all base-relative urls to root-relative urls.

**Comment by mingir2** [comment]
If we use base-relative url, the header component won't work because index.html is served from https://ar-js-org.github.io/studio/ whereas marker.html and location.html are not. So, using ../assets/img/logo.png won't work on the landing page. This is why I made changes to use root-relative urls.

But then, If we use root-relative url, we can't use https://ar-js-org.github.io/studio because the root url is https://ar-js-org.github.io/.

Here are few possible solutions
- Rename the "studio" repo to "ar-js-org.github.io", so that everything is served from the root url.
- Use a custom domain.
- Revert back to base-relative urls and try to fix the header component.

**Comment by kalwalt** [comment]
Hi @mingir2 i have fear that the first option `Rename the "studio" repo to "ar-js-org.github.io", so that everything is served from the root url.` could break links for Ar.js (camera_para.dat, patt.hiro...) maybe preferable the other options. Bu if you add a `../ ` to the links won't works?

**Comment by mingir2** [comment]
@kalwalt I see. `../` works well for most of the links, but it breaks the current implementation of the header component.

**Comment by nicolocarpignoli** [comment]
I fixed using a custom attribute where you specify the 'assets' folder URL for the web components instance. Can be enhanced in the future but for now at least it works (if someone reaches the online version at least does not see errors).
