### ISSUE TITLE
Change uploaded files properties (see description)

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/studio#32]
For the MVP, we should change, if possible, the sizes and rotation of GLTF files uploaded (also 2D video and 2D images).

* for GLTF, we have to change sizes if too big, and define a standard size
* same for 2D videos
* same for 2D images

and for every of them, position should be set at "0,0,0" while rotation should be made so the content is perpendicular to the marker.

This changes are not to be done, obviously, on the source file the user uploaded: we should take the sizes, rotation and position of the given content, and knowing the output we want, we should cable the scale, rotation and position properties according to this data.

E.G.

We set '100' as default size for Images.

If the users loads a 200px images, we should call the backend with scale parameters data, in this way:

`scale: "0.5, 0.5, 0.5"`

**Comment by faace** [comment]
There are implemented on branch issue #38.

**Comment by nicolocarpignoli** [comment]
@faace about this, it's implemented meaning that now the viewer shows any assets with a good ratio/size. That's correct. But we have to understand what's the scale/rotation we have used, in order to pass it to the backend side, so the backend can generate those properties on the final template. Are you able to do this, too? Maybe on that very same PR.

**Comment by faace** [comment]
@nicolocarpignoli I can pass the size of the model/video/jpg to the backend. It is better that the backend side defines what kind of format I should pass. Then I can follow it.
