### ISSUE TITLE
Create marker based experience

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/studio#36]
On marker based page, connect the frontend with backend in order to create html marker based experience

**Comment by nicolocarpignoli** [comment]
I think @RomanKlimov have already sorted this out. Let us know

**Comment by RomanKlimov** [comment]
Yes, but only for image type markers. I used @mingir2 code for preview images and pushed it all on feature/marker_based_exp_for_image. There is still some refactoring and debugging work. I think we can continue adding other marker types together)

**Comment by mingir2** [comment]
@nicolocarpignoli @RomanKlimov Agree. 

We have to add support for other types and add file validations as well for error checking.
