### ISSUE TITLE
Create 'publish the project' page

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/studio#44]
When clicking on the footer, on 'Publish on Github', we should navigate to the publication page
The integration of logic should be handled on a separate issue: https://github.com/AR-js-org/studio/issues/8

So this actual issue is more like related to create the page, buttons, UI elements.

![image](https://user-images.githubusercontent.com/22395670/78658847-02ddb580-78cb-11ea-925d-d5dce4d7126a.png)

**Comment by nicolocarpignoli** [comment]
@le0m @RomanKlimov this is probably changed due to latest decision.
@fcor do you read on Slack about that? We will not need the first paragraph (so no login on github, we will use a pre-define AR.js Studio account for every user).

**Comment by fcor** [comment]
> 
> 
> @le0m @RomanKlimov this is probably changed due to latest decision.
> @fcor do you read on Slack about that? We will not need the first paragraph (so no login on github, we will use a pre-define AR.js Studio account for every user).

Sounds good, I'll work on this one tomorrow 😀
