### ISSUE TITLE
Change instructions text (and add more?)

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/studio#46]
I think we should enhance text instructions on the home page and on the location/marker pages.

I will look into this when all functionalities have been implemented.

We should use a language understandable for everyone, teachers, students, artists, passionate users without coding knowledge.

**Comment by Annasmerag** [comment]
I totally agree! I have been silently tweaking some of the copy on the Figma file as we've been moving along, with wide accessibility in mind. Let's definitely take a moment to refine the final text once the functionality is there.

**Comment by nicolocarpignoli** [comment]
Another thing: we should specify how a marker can be. So the features of a valid image to be uploaded as marker image.
Maybe I can make a Medium article that specifically talk only about this, in short.

**Comment by Annasmerag** [comment]
I was wondering...wanted to write something about it but realized I have no idea what the best practices are for this.

**Comment by nicolocarpignoli** [comment]
I will do that, you can make it more readable and in a better form :)

**Comment by Annasmerag** [comment]
There are a couple new notes on the Figma file. ;) Among them, I think it will be a good idea to add a link to the AR.js documentation at the bottom of each page. 👍

**Comment by nicolocarpignoli** [comment]
We will open new, specific issues for every action, starting from feedbacks.
