### ISSUE TITLE
Added multiple pick location on Location Based page

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/studio#48]
It should be possible to add more places on location based, following the Figma Design:

https://www.figma.com/file/TUjZ2KYsmhA5LUkt9KIhcB/ARjs-Studio?node-id=0%3A1

![image](https://user-images.githubusercontent.com/22395670/79962054-deb3d400-8487-11ea-83ee-0133e9c20424.png)

**Comment by nicolocarpignoli** [comment]
From Design channel on Slack:

The idea was a location added in the map interface would automatically be added to the list above [the locations list], and a location with manually entered lat/long would automatically appear as a pin on the map...so in order to delete a pin you would find the corresponding number on the list and delete it from there.

**Comment by ba5eem** [comment]
I started working on this - most functionality is there, adding multiple and removing, updating, deleting, etc. I need to fix some errors and add the labels to marker icons before PR ;also do a clean up on code.

**Comment by nicolocarpignoli** [comment]
@ba5eem Hi there! Any update on this one? :)

**Comment by ba5eem** [comment]
Im close to done with it, just struggling with some state issues for multiple scenarios.

**Comment by nicolocarpignoli** [comment]
Sorry to bother @ba5eem are you able to push this forward? I can help if you need assistance. 16th of June we have a presentation and everything should be done for the MVP :) 
Let me know

**Comment by ba5eem** [comment]
Not a bother at all, I totally have let the team down on this one. I worked on it some this weekend and decided maybe i should re-vamp it and figure the proper way to do this with shadow dom by following docs/guides etc., but its still proving to be a challenge for me. Good to know about the MVP - ill work on it more today and tomorrow, if I cant figure it out, help would be nice. Ill let you know ASAP.

**Comment by nicolocarpignoli** [comment]
@ba5eem if you can take a look at the AR.js Studio Slack channel: technical-stuff it would be great :D
