### ISSUE TITLE
On Marker based, Show marker image on Final publication/output step

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/studio#51]
We should show the final marker image to be scan on the final step, so the user know what he has to print/display with the generated code. Thanks to @gciandro13 for the suggestion

**Comment by gciandro13** [comment]
Yeah, I think that would be very useful for the final user. 
Many ways to do it: for example, we can give him a link, after the download, specifying that it will be what he had to print/display for working properly. 
The same flow should be worked on "Publish on Github" case, I think.

**Comment by nicolocarpignoli** [comment]
waiting for designers sketch.
