### ISSUE TITLE
Add feedbacks on publish page (marker)

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/studio#53]
As Designs, we have to add some feedback on current publish page, and create two publish pages that differs (the marker will show the final marker image to be downloaded, the location page will show the locations on the map).

Details at Design Figma file: https://www.figma.com/file/TUjZ2KYsmhA5LUkt9KIhcB/ARjs-Studio?node-id=0%3A1

![image](https://user-images.githubusercontent.com/22395670/82296244-3410d180-99b1-11ea-863e-75c264ef7bac.png)

![image](https://user-images.githubusercontent.com/22395670/82296267-3d9a3980-99b1-11ea-893a-cc856e77e788.png)

**Comment by nicolocarpignoli** [comment]
this issue extends this one: https://github.com/AR-js-org/studio/issues/51

**Comment by nicolocarpignoli** [comment]
@mingir2 As we discuss yesterday, we should also add the line

`We don’t own your content! Write us at arjsstudiohelp@gmail.com’ and we will delete it`

The account is real, I just created it.

**Comment by mingir2** [comment]
@nicolocarpignoli where should this disclaimer placed?

**Comment by Annasmerag** [comment]
I'd say at the bottom of the publish-success page. I can add it to the figma file.
