### ISSUE TITLE
Zapworks Studio

### ISSUE THREAD

**Issue by marcusx2** [AR-js-org/studio#55]
Please take a look at [Zapworks Studio](https://zap.works/studio/). It would be great if this studio could offer similar functionalities, such as timeline, etc.

**Comment by nicolocarpignoli** [comment]
Thanks! Interesting :) 

Future plans can be seen on the 'projects' section of this repository. You can write us a feedback for specific requests: https://docs.google.com/forms/d/e/1FAIpQLSc1df2EwYNqL0jv2z8hLmXETsvQ7MUg1W4SKNDPdgo-vvKTVg/viewform?usp=send_form

Thanks
