### ISSUE TITLE
Define a basic design system

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/studio#6]
We should define a basic design system, setting

- font family and font weights
- colors
- column size
- other variables

**Comment by nicolocarpignoli** [comment]
@sigalor do you want to take this task and work together with Jonas maybe?

**Comment by nicolocarpignoli** [comment]
@jonasjohansson as soon as you have accepted the invitation you can self assign this to you. @sigalor and me can help you if needed 😁

**Comment by jonasjohansson** [comment]
Awesome, will have a look at it this weekend!

**Comment by nicolocarpignoli** [comment]
@jonasjohansson how this is going? If you need help just ask :)

**Comment by nicolocarpignoli** [comment]
we should define our choice - so stuff used for now in the Public foder, as variables on scss/css files, in order to have something defined

**Comment by mingir2** [comment]
Wikimedia's design style guideline is a pretty good start for this. It's very simple.

https://design.wikimedia.org/style-guide/

**Comment by nicolocarpignoli** [comment]
to update: collaborative design work is happening here => https://www.figma.com/file/TUjZ2KYsmhA5LUkt9KIhcB/ARjs-Components?node-id=0%3A1

**Comment by nicolocarpignoli** [comment]
Design work, as for a 'design system' can be considered closed, for now. It's possible to find design files on the Readme. Thanks to everybody!
