### ISSUE TITLE
Marker Page: back button

### ISSUE THREAD

**Issue by gciandro13** [AR-js-org/studio#64]
The yellow back button in "marker/index.html" that I see in production does not work as expected. 
No error; seems it has to be developed.
I can take it into account @nicolocarpignoli

**Comment by nicolocarpignoli** [comment]
Is it only marker page or also location and other pages  (like publish) ?

**Comment by gciandro13** [comment]
The same bug is present also in location and publish page.. don't know about other pages.
What is the priority?

**Comment by nicolocarpignoli** [comment]
very low. it works sometimes, we should go in depth and see why this happens.

**Comment by gciandro13** [comment]
![screenBugBack jpeg](https://user-images.githubusercontent.com/20702863/83426097-ee331f00-a42e-11ea-80b8-00d455ce9a2c.jpg) 

I could go back only by click the red zone. I will investigate it

**Comment by nicolocarpignoli** [comment]
great

**Comment by Annasmerag** [comment]
Only by clicking directly on top of the arrow does the back button work.

**Comment by gciandro13** [comment]
@Annasmerag yes we will take it into account. 

This issue will be close ( moving to "Responsive Layout" issue).
