### ISSUE TITLE
Github publish integration

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/studio#65]
* ask user for project-name
* login with OAuth on Github
* integrate backend
* when backend answers back, show repository url to user as feedback.

**Comment by le0m** [comment]
We deployed https://github.com/prose/gatekeeper to Heroku to handle the backend process of exchanging the `code` for a `token`.

How to use:
- call `https://arjs-studio-backend.herokuapp.com/authenticate/<INSERT_CODE_HERE>` with the code obtained from GH
- the service will reply with a JSON object containing the `token`
- use that token when serving files to GitHub (see [docs](https://github.com/AR-js-org/studio-backend/blob/master/docs/providers.md) for `serveFiles()` method of GitHub provider)

**Comment by nicolocarpignoli** [comment]
Done! Works great. Thank you all for the great great work!
