### ISSUE TITLE
Publish on github: bug with img content

### ISSUE THREAD

**Issue by gciandro13** [AR-js-org/studio#66]
Hi, 
I tried to create a marker based experience (with the default marker), uploading an image as content (jpg and then png), but it seems that pubblication on github doesn't work.
In particular, studio stucks on publish page with a strange error in Chrome Inspector.

Attachments:

This is the png image.
![PNG IMAGE TRIAL](https://user-images.githubusercontent.com/20702863/83628949-9533ca00-a599-11ea-886a-a53eda087833.png)

This is the jpeg image.
](https://user-images.githubusercontent.com/20702863/83628909-89e09e80-a599-11ea-98c3-bfe155096737.jpg)

Studio stucks here.
![studioStuck](https://user-images.githubusercontent.com/20702863/83629033-ba283d00-a599-11ea-9fcb-fb8e472c3ed3.jpg)

Inspector when studio is stucked.
![inspectorBug](https://user-images.githubusercontent.com/20702863/83629067-c7452c00-a599-11ea-8194-111b791eb2cd.png)

**Comment by dandes97** [comment]
If I'm not mistaken this parameter has to be only set in the case of a 3D-model/gltf-model, right? It's an error in the backend, that's for sure. I guess the easy solution is just by doing this?

Screenshot 2020-06-03 at 13 53 11

Which only handles the error in case of a 3D-asset.
I've made a seperate issue for this :).

**Comment by dandes97** [comment]
If I'm not mistaken this parameter has to be only set in the case of a 3D-model/gltf-model, right? It's an error in the backend, that's for sure. I guess the easy solution is just by doing this?

<img width="456" alt="Screenshot 2020-06-03 at 13 53 11" src="https://user-images.githubusercontent.com/29202791/83634475-e72d1d80-a5a2-11ea-99b3-6a2ed900c49f.png">

Which only handles the error in case of a 3D-asset and then fixes the problem.
I made a seperate issue for this :)

**Comment by le0m** [comment]
let's continue this on #67
