### ISSUE TITLE
studio back-end error : asset parameters not valid

### ISSUE THREAD

**Issue by dandes97** [AR-js-org/studio#67]
Downloading a package with gltf-model (zip-package) as content works great, but when I want to download a package with other content(video/image)I receive the error: "Asset parameters are not valid"
<img width="417" alt="Screenshot 2020-06-03 at 13 47 17" src="https://user-images.githubusercontent.com/29202791/83633603-80f3cb00-a5a1-11ea-8716-e4218e69891c.png">

If I'm not mistaken this parameter has to be only set in the case of a 3D-model/gltf-model, right? It's an error in the backend, that's for sure. I guess the easy solution is just by doing this?

<img width="456" alt="Screenshot 2020-06-03 at 13 53 11" src="https://user-images.githubusercontent.com/29202791/83633667-9963e580-a5a1-11ea-9351-639bfe81baa1.png">

Which only handles the error in case of a 3D-asset.

**Comment by le0m** [comment]
Hi, thanks for the feedback.
I thought that parameter meant if the asset was good to be used or not, sorry for the misunderstanding.

If this parameter is used to tell backend that It can use the other `assetParam`, I think It can be avoided. Backend should throw exceptions if a package has wrong/missing `assetParam` set.

**Comment by dandes97** [comment]
Right, I think I see what you mean. Thanks for explaining! I see it is also resolved now, so I guess this issue can be closed. :)
