### ISSUE TITLE
Purchasing domain (www.arjs.studio) for repo

### ISSUE THREAD

**Issue by jonasjohansson** [AR-js-org/studio#7]
Would be great to have a short URL connected to our repo which we can use for demos and examples, while also looking a bit more legit.

www.arjs.studio is 30 euros per year on Godaddy.

**Comment by kalwalt** [comment]
@jonasjohansson cool idea!

**Comment by nicolocarpignoli** [comment]
If I remember correctly, on namecheap.com the first year of a domain can be bought for ~9 dollars. Actually https://www.namecheap.com/ is down for me 😞  We can see next days

**Comment by fcor** [comment]
~21 USD now on namecheap

**Comment by spartalisdigital** [comment]
when the location and the purchase value for the domain is defined, let them know and request payment by Paypal so that each one can collaborate with a little money.

**Comment by spartalisdigital** [comment]
if possible at least we will leave the domains reserved until purchase to preserve them.

**Comment by thauska** [comment]
I think we better wait a little longer to buy the domain

**Comment by gciandro13** [comment]
I checked on namecheap , still 21 USD. 
I don't know if it necessary for the MVP to buy it , or, at least, think about that later

**Comment by nicolocarpignoli** [comment]
Not relevant as for now. We will think of this in the future
