### ISSUE TITLE
marker based ar not working on pixel 4 xl

### ISSUE THREAD

**Issue by heikog** [AR-js-org/studio#79]
I used ar.js studio to create this:

https://ar.3dtwins.de

it should react to the default marker:

https://github.com/AR-js-org/studio/blob/master/assets/default-marker.png

but for some reason, it's not working. (It works on with my notebook browser/camera but not with my pixel 4xl)

Can anybody help?

**Comment by mingir2** [comment]
I tested it with a Pixel 3a and got it working on Chrome. Which browser are you using on the Pixel?

**Comment by nicolocarpignoli** [comment]
Hi @heikog, please re-open the issue providing us the full code, and full  specs of your device (also Browser). thank you

**Comment by heikog** [comment]
I am using the default Chrome browser on the Pixel 4XL
I compared it with the iPhone X: it works on the iPhone. The Marker in the camera preview of the Pixel 4 looks much bigger than in the camera preview of the iPhone. maybe that's an issue?
