### ISSUE TITLE
Github OAuth authorization

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/studio#8]
As @le0m pointed out here: https://github.com/AR-js-org/studio-backend/issues/6#issuecomment-575935742

On the studio frontend side, we should interact with Github APIs to request authorization in order to make some actions (retrieve the token, create repository, push on it).

**Comment by le0m** [comment]
The backend component works with any kind of token, as long as the scope `repo:public_repo` is authorized by the user.

See this library to implement retrieving a Personal Access Token: https://github.com/octokit/auth-basic.js#readme

**Comment by le0m** [comment]
For the MVP, we decided to use a new GitHub account to generate a token, and hard-code that account/token into the Studio app.
When users create a project from Studio and decide to host it on GitHub, we'll use this account and create a new repository for deploying and hosting the project.

**Comment by nicolocarpignoli** [comment]
@le0m do we need to do something on frontend side or we will do that on the backend? If we go for the latter, we can close this one.

**Comment by le0m** [comment]
You're right, we can close this one

**Comment by le0m** [comment]
> The backend component will work with any kind of token, as long as the scope `repo:public_repo` is authorized by the user.
> 
> See this library to implement retrieving a Personal Access Token: https://github.com/octokit/auth-basic.js#readme

we decided to go back to this solution
