### ISSUE TITLE
Handle spaces on uploaded file name

### ISSUE THREAD

**Issue by cytchemsir** [AR-js-org/studio#82]
When I upload a project in AR.js studio, I find I cannot finish the final step of publishing the project in Github. I wait for a long time in that page but I cannot see the final link for my project. (Always display "We are all set! We are publishing your AR Experience. Please wait few seconds .. ")

**Comment by thauska** [comment]
I've the same problem. Have open the console and he show this:

![Capturar](https://user-images.githubusercontent.com/8525721/86312721-b7048900-bbf9-11ea-8345-de544eaf680c.PNG)

**Comment by thauska** [comment]
https://github.com/thauska/robot-defenderbeoeve

**Comment by thauska** [comment]
I think I know what the problem is. The GLB file cannot have spaces into his name. I made a new test, renaming the file without spaces before uploading.

**Comment by nicolocarpignoli** [comment]
That's great, thanks @thauska I will specify this on the issue title

**Comment by faace** [comment]
I have tried to upload glb which name has spaces and succeeded. Could someone send me an issue glb? faace@qq.com.

**Comment by nicolocarpignoli** [comment]
Other people told this to me. 
I think that's not easy to handle as gltf has references 'inside' the assets. I will add a disclaimer to state to control the filename before upload it.
