### ISSUE TITLE
Project cannot work when I download project package

### ISSUE THREAD

**Issue by cytchemsir** [AR-js-org/studio#83]
I finished all the work to make a project in AR.js studio. When I published on Github, the project can be run properly.
When I save your project locally and download the package containing the generated code and all supporting files.
I put all the files in my webpage. I found that the project cannot run properly (When the marker is put in front of the camera,
the glb model cannot displayed)

Anybody can help me!

**Comment by nicolocarpignoli** [comment]
Hi @cytchemsir please share with us the code, we will try and see if the problem is on the generated code or something else from your side.

**Comment by nicolocarpignoli** [comment]
Re-open the issue with more details, thank you!

**Comment by cytchemsir** [comment]
I use the AR-js studio to create a project using my own marker.
How to change (decrease) the width of black broader in the marker?

Remark: I just know how to do the project using AR-js studio. I don't know
coding.

Nicolò Carpignoli <notifications@github.com> 於 2020年7月6日 週一 下午8:23寫道：
