### ISSUE TITLE
How to change (decrease) the width of black broader in the marker?

### ISSUE THREAD

**Issue by cytchemsir** [AR-js-org/studio#85]
I use the AR-js studio to create a project using myself marker. 
How to change (decrease) the width of black broader in the marker?

Remark: I just know how to do the project using AR-js studio. I don't know coding.

**Comment by thauska** [comment]
This is something that cannot be done with AR.js Studio yet. Maybe in the future.

**Comment by nicolocarpignoli** [comment]
Yes, we will add these feature in the future. I will write down the specific issue next days.

**Comment by gciandro13** [comment]
https://github.com/AR-js-org/studio/issues/96
