### ISSUE TITLE
How to display two 3D objects in the same scene using two markers?

### ISSUE THREAD

**Issue by cytchemsir** [AR-js-org/studio#86]
How to display two 3D objects in the same scene using two markers?
Thx

**Comment by fcor** [comment]
Hi, you can use HIRO and KANJI presets:

```html
<a-marker preset="hiro">
    <a-entity
      position="0 0 0"
      scale="0.05 0.05 0.05"
      gltf-model="model1"
    ></a-entity>
</a-marker>

<a-marker preset="kanji">
    <a-entity
      position="0 0 0"
      scale="0.05 0.05 0.05"
      gltf-model="model1"
    ></a-entity>
</a-marker>
```

You can also use barcodes, which allows you to use even more markers if needed. 

Check this out: https://medium.com/@nicolcarpignoli/how-to-deliver-ar-on-the-web-only-with-a-qr-code-139bb90e82f1

**Comment by nicolocarpignoli** [comment]
@cytchemsir it's not possible out-of-the-box of AR.js Studio but you can take the generated code and modify it as Fabio suggested. It's totally possible with AR.js.

Please check this out: https://ar-js-org.github.io/AR.js-Docs/ (look for Marker Based)

**Comment by cytchemsir** [comment]
I want to display two glb files at the same time and the two models can
rotate/zoom/translate freely using two different markers
Can anyone help me?
Many thanks!

Fabio Cortés <notifications@github.com> 於 2020年7月9日 週四 上午6:28寫道：
