### ISSUE TITLE
o código hiro não está funcionando quando aponto a Câmera

### ISSUE THREAD

**Issue by naluz7** [AR-js-org/studio#87]
Estou fazendo todo procedimento corretamente no AR js studio, veja link: https://ar-js-org.github.io/studio/pages/publish-confirm/index.html?code=296306096d2280e233c0&state=9e7nh4 
mas quando o link abre e a câmera funciona, aponto o código hiro para câmera  mas não aparece  a imagem AR, já fiz vários links mas não está funcionando.
O que está ocorrendo? como posso resolver  isso?
![AR_links-gerados](https://user-images.githubusercontent.com/38086697/86912704-d9177300-c0f3-11ea-86ff-e7f2cf7e009b.jpg)

**Comment by thauska** [comment]
Bom dia, @naluz7 . Qual navegador e SO estás usando?

**Comment by naluz7** [comment]
google Chrome e Iphone 6

**Comment by thauska** [comment]
Existe essa limitação do Chrome no iOS. Para iOS, só funciona se estiver no browser Safari.

**Comment by thauska** [comment]
https://dev.to/thauska/ar-js-studio-realidade-aumentada-na-web-baseado-em-marcadores-g0n

Aqui tem um tutorial em português de como utilizar o AR.js Studio baseado em marcadores.

**Comment by thauska** [comment]
Alguma outra dúvida? Testou com Safari?

**Comment by naluz7** [comment]
vou testar daqui a pouco. Se eu precisar que desenvolva para mim algo em AR podemos conversar?

**Comment by naluz7** [comment]
não está aparecendo a AR, salvei com letras ninúsculas como orienta o tutorial. No teste com o link do tutorial aparece a imagem que você colou, alguma coisa estou fazendo errado. Qual o tamanho(resolução) da imagem do arquivo que devo enviar? seja em png, jpeg, 3D, vídeos?

**Comment by thauska** [comment]
Você subiu a imagem Hiro para gerar marcador?

**Comment by naluz7** [comment]
sim, tem como enviar um vídeo que fiz demonstrando ?:

**Comment by thauska** [comment]
Chegou fazer o download da imagem Hiro que você subiu no AR.js Studio?

**Comment by naluz7** [comment]
agora consegui ver um, não sabia que cada código só vale para aquele arquivo. Vou testar corretamente agora e te falo.

**Comment by naluz7** [comment]
Muito grato pela sua atenção! Você conhece o piso interativo? Aquele que usa um sensor para captar movimentos e projeta efeitos no chão?

**Comment by thauska** [comment]
Não conheço. Mas se quiser estender mais a conversa, tem o chat no Gitter. Lá tem bastante gente para ajudar. Irei finalizar essa issue, já que seu problema foi resolvido. No Gitter tem como estender mais conversas. Um abraço!

https://gitter.im/AR-js/Lobby

**Comment by naluz7** [comment]
Vou entrar amanhã lá, você estará lá?

**Comment by thauska** [comment]
sim. Estarei

**Comment by naluz7** [comment]
Boa tarde Thayana!

**Comment by naluz7** [comment]
visualizei o link do Chat mas antes gostaria de fazer algumas perguntas sobre AR, nossa conversa de ontem, é possível?
