### ISSUE TITLE
Add "Send feedback" sticky button

### ISSUE THREAD

**Issue by Annasmerag** [AR-js-org/studio#88]
To make it more easily accessible, can we change the "send feedback" button to a yellow sticky button (so it doesn't scroll) in the lower right corner of all the pages?
<img width="367" alt="Screenshot 2020-06-17 at 10 30 02" src="https://user-images.githubusercontent.com/36634421/86958954-d62b7b00-c111-11ea-9b43-390e7cd0b01c.png">

**Comment by thauska** [comment]
I can handle this. For UX is better to have an sticky button for feedback.

**Comment by thauska** [comment]
@nicolocarpignoli what do you think about this? can i implement this?

**Comment by nicolocarpignoli** [comment]
yea please ! :D

**Comment by gciandro13** [comment]
Hi @thauska how it is going ? Are you still workin' on it? ;)

**Comment by thauska** [comment]
Hi there. I've create an float button component for this. I'm pushing tonight my branch.

**Comment by thauska** [comment]
![screencapture-127-0-0-1-5500-index-html-2020-09-16-16_29_55](https://user-images.githubusercontent.com/8525721/93383406-f6766500-f839-11ea-8dc0-c4c7e70254db.png)

**Comment by thauska** [comment]
Is this good?

**Comment by gciandro13** [comment]
Sounds good to me... what is your opinion @Annasmerag ?  

@thauska responsive design is the same? Can you please open pull request when Anna is agree and you'reready? :) 

Thanks a lot

**Comment by Annasmerag** [comment]
Should do the trick! Is it persistent on all the pages?

**Comment by thauska** [comment]
Yes. It is an component and can be placed on all pages.

**Comment by gciandro13** [comment]
For me it is great! Feel free to open PR when you want, so that I will check it ! 

Thanks for your job @thauska

**Comment by thauska** [comment]
PR sended. #100
