### ISSUE TITLE
Boa tarde Thayana!

### ISSUE THREAD

**Issue by naluz7** [AR-js-org/studio#89]
Boa tarde Thayana!

_Originally posted by @naluz7 in https://github.com/AR-js-org/studio/issues/87#issuecomment-656259214_

**Comment by naluz7** [comment]
Gostaria de tirar algumas dúvidas sobre AR, posso perguntar?

**Comment by thauska** [comment]
Qual a dúvida?

**Comment by naluz7** [comment]
Como faço para inserir código de comandos e opções de: áudio, gif sem fundo animação, vídeo com chroma key  para tirar o fundo, botão sair e camadas independentes?

**Comment by thauska** [comment]
Com o AR.js Studio não dá pra fazer isso. Veja a documentação do AR.js mesmo: 

https://ar-js-org.github.io/AR.js-Docs/

**Comment by naluz7** [comment]
Onde seria possível fazer dessa forma? Você sabe fazer? se sim quanto custa para fazer dessa forma com comandos?

**Comment by naluz7** [comment]
Bom dia Thayana!
Você trabalha com google AR?

**Comment by naluz7** [comment]
Bom tarde Thayana!

**Comment by naluz7** [comment]
Estou procurando algum programador do ARcore, você conhece alguém?

**Comment by thauska** [comment]
Esse espaço de issues é para trabalho e organização pro desenvolvimento da plataforma AR.js Studio. Seria bom me procurar fora daqui. tem como mandar email? thayanacmamore@gmail.com

**Comment by naluz7** [comment]
Ok
