### ISSUE TITLE
Problems about display of .glb file in web (ios)

### ISSUE THREAD

**Issue by cytchemsir** [AR-js-org/studio#91]
I am a teacher and I want to use AR in web for teaching purpose.
When I use Ar.js studio to display a .glb model publish in Github, the model can be
displayed under my own marker. This is very amazing!

However, if I download the package and host in my own website, the program cannot run normally. Very frustrating. I enclosed the whole zip file for your reference. Can you help me to see is there any problem?

Another question is that I don't know how to write javascript. Can anybody give me the whole html file (with javascript embed) so that I can display two different .glb files (models) using two different custom markers.

Many thanks!

**Comment by thauska** [comment]
What's the URL from ur website?

**Comment by cytchemsir** [comment]
https://drv.tw/~cytchemsir@gmail.com/gd/AR/index.html
<https://drv.tw/~cytchemsir@gmail.com/gd/web/index5.html>

By the way, can you teach me the whole html file (with javascript embed) so
that I can display two different .glb files (models) using two different
markers (preset/custom) in the same scene. The two models can be
rotated/zoomed/translated freely.

Many thanks.

Thayana Correa Mamore <notifications@github.com> 於 2020年7月13日 週一 上午3:17寫道：

**Comment by thauska** [comment]
I've see the console and it says that the patt file can't be find:

![Capturar-2](https://user-images.githubusercontent.com/8525721/87793745-09f65700-c81c-11ea-9d5f-f6d8ce6afc96.PNG)

**Comment by gciandro13** [comment]
Hi @cytchemsir  .. still stuck with the bug? @thauska are you going further with the investigation?

**Comment by nicolocarpignoli** [comment]
@cytchemsir please open a new issue with more details. The problem is probably with the code references to the assets.
Upload the full code on a github repo and link us the repo OR upload the zip somewhere so we can download it and inspect it. Thank you.
