### ISSUE TITLE
.glb models exported from blender 2.82 appear dark in AR.js Studio

### ISSUE THREAD

**Issue by thebioway** [AR-js-org/studio#92]
Using blender 2.82 with built-in gLTF 2.0 exporter. Exported 3D object as .glb file and whenever I'm uploading it through choose the content option in AR.js studio, in the preview window besides it appear as a very dark model.
Checked the exported file with viewer available at https://gltf-viewer.donmccurdy.com/, model appear normal as it should.
Models downloaded from Sketchfab work normal. So what is the issue now?

Model exported from blender
[https://github.com/thebioway/watertest1yneieh/blob/gh-pages/assets/asset.gltf](url)

**Comment by nicolocarpignoli** [comment]
The issue could be that we have chosen a different light than the one of Don McCurdy's GLTF viewer. And so you see them 'darker'.
