### ISSUE TITLE
Enhance UI flow to make it more easier 

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/studio#94]
From Mirek's feedback with german teachers, we found out that for some users the creation flow is not very understandable. Sometimes users think that all the flow is in one page, and the uploaded marker  (on the first step) is the final output.

Recurrent point:

- Download marker = Download asset ---> That was often a problem. They thought that downloading the marker means downloading the zipped content. Had to explain them several times. 

- How to go on after d/l the zipped project? I created an upload/unzip/create QRCode page for my participants, see https://www.hancl.de/ar/upload.html (edited)

We may think of changing the UI flow (maybe a top-bottom flow instead of left-right?).

**Comment by gciandro13** [comment]
@nicolocarpignoli  I will edit this issue with more Mirek's feedback (more precise)

**Comment by franbrennan** [comment]
![issues_vidPoster](https://user-images.githubusercontent.com/3405072/100329303-65540500-2fc5-11eb-9890-77506243bdd2.jpg)

- - -
### A Few Thoughts (via video overview)

The vid can be found at: https://youtu.be/p4DF8sO4brQ

**Comment by gciandro13** [comment]
Will be close in https://github.com/AR-js-org/studio/issues/108
