### ISSUE TITLE
Location based is not working in the deployed project

### ISSUE THREAD

**Issue by hassanayoub85** [AR-js-org/studio#98]
hi,
I created a demo project with a location far approx 15km of my place, when i look into that place in the deployed project, i didnt saw the image.
Thanks

**Comment by nicolocarpignoli** [comment]
Hi, you have to modify the project in order to use a place more distant than ~1km

See this example:

https://github.com/AR-js-org/AR.js/blob/master/aframe/examples/location-based/arjs-webcam-texture/index.html
